---

- name: ensure chronyd is installed
  yum:
    name: chrony
    state: present

- name: creating chronyd.conf configuration file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: true

- name: start and enable the chronyd service
  service: name=chronyd state=restarted enabled=yes
